name: Build and Upload wimldr

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          # Update package list and install required tools
          sudo apt-get update
          sudo apt-get install -y parted dosfstools qemu-utils build-essential gcc-aarch64-linux-gnu

      - name: Build wimldr
        working-directory: wimldr
        run: |
          make

      - name: Run pack-hda.sh script
        run: |
          chmod +x pack-hda.sh
          sudo ./pack-hda.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: wimldr
          path: |
            wim.qcow2
            wim.cpio
            wimldr/wimldr.x64
            wimldr/wimldr.ia32
            wimldr/wimldr.aa64
            wimldr/wimldr
